services: 
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=akif
      - MONGO_INITDB_ROOT_PASSWORD=intiharet
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: